# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bookscrape',
                'doc_host': 'https://dvths.github.io',
                'git_url': 'https://github.com/dvths/bookscrape',
                'lib_path': 'bookscrape'},
  'syms': { 'bookscrape.core': {'bookscrape.core.foo': ('core.html#foo', 'bookscrape/core.py')},
            'bookscrape.items': {},
            'bookscrape.middlewares': {},
            'bookscrape.pipelines': {},
            'bookscrape.settings': {}}}
